### PR TITLE
fixed issue

### PR DESCRIPTION
**Pull request by johnmarksinclair**
## Purpose

Removed back gesture - allowed user to sign out unintentionally 

## Proposed Change

Disabled swipe gestures for navigation

## Checklist

- [x] Disable gesture navigation

### CODE REVIEW

**Comment by lexesj** [comment]
Might be due to Android, but I can still use the back gesture and unintentionally logout. Can someone else confirm?

**Comment by johnmarksinclair** [comment]
> Might be due to Android, but I can still use the back gesture and unintentionally logout. Can someone else confirm?

ah weird i'll take another look tomorrow

**Comment by johnmarksinclair** [comment]
> Might be due to Android, but I can still use the back gesture and unintentionally logout. Can someone else confirm?

can you check again the gesture disable should work so I've added it to the individual screens

**Comment by lexesj** [comment]
> > Might be due to Android, but I can still use the back gesture and unintentionally logout. Can someone else confirm?
> 
> can you check again the gesture disable should work so I've added it to the individual screens

Unfortunately it still doesn't work for me. Looks like the fix can only be applied to `IOS` only.

image

**Comment by johnmarksinclair** [comment]
> 

ah just have to re-jig the nav setup then

**Comment by lexesj** [comment]
Superseded by #25.

**Pull request closed without merging**
